version: '3.7'

services:
  mongo:
    container_name: MA_mongo
    image: mongo
    restart: always
    command: mongod --quiet
    env_file:
      - mongo-variables.env

  mongo-express:
    container_name: MA_mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - mongo-variables.env

  # server:
  #   stdin_open: true
  #   container_name: MA_frontend_server
  #   image: node
  #   volumes:
  #     - ../frontend:/usr/src/app:z
  #     - '/app/node_modules'
  #   ports:
  #     - 3080:3000
  #   command: npm run build

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - './frontend/:/app'
      - './frontend/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true